---
- name: Installation and Configuration cluster
  hosts: all
  become: yes
  gather_facts: True

  vars_files:
    - vars/main.yml

  roles:
    - general
    - { role: master, when: node == "master"}
    - { role: worker, when: node == "worker"}