---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-basic-auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-basic-auth
  template:
    metadata:
      labels:
        app: demo-basic-auth
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: httpbin
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-basic-auth
spec:
  selector:
    app: demo-basic-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
